IF EXISTS (SELECT name
   FROM   sysobjects
   WHERE  name = 'proknjizi_prometni_dokument' AND type = 'P')
   DROP PROCEDURE [proknjizi_prometni_dokument]
GO

CREATE PROCEDURE dbo.[proknjizi_prometni_dokument]
   @PIB char(12),
   @GODINA numeric(4),
   @BROJ_PROMETNOG_DOKUMENTA numeric(5)
AS

	DECLARE
		@BROJ_TRANSAKCIJA int,
		@PORUKA varchar(100)

	IF (SELECT STATUS
		FROM PROMETNI_DOKUMENT
		WHERE BROJ_PROMETNOG_DOKUMENTA = @BROJ_PROMETNOG_DOKUMENTA AND PIB = @PIB AND GODINA = @GODINA) <> 'F'
	BEGIN
		RAISERROR('Nije dozvoljeno knjizenje prometnog dokumenta koji nije u fazi formiranja!', 11, 2)
		RETURN
	END
	
	IF (SELECT COUNT(*)
		FROM STAVKA_PROMETNOG_DOKUMENTA
		WHERE PIB=@PIB AND GODINA=@GODINA AND BROJ_PROMETNOG_DOKUMENTA=@BROJ_PROMETNOG_DOKUMENTA)<=0
	BEGIN
		RAISERROR('Dokument mora da ima bar 1 stavku', 11, 2)
		RETURN
	END
	
	IF (SELECT ZAKLJUCENA
		FROM POSLOVNA_GODINA
		WHERE PIB = @PIB AND GODINA = @GODINA) = 1
	BEGIN
		RAISERROR('Godina ne sme biti zakljucena', 11, 2)
		RETURN
	END
	
	IF (SELECT DATUM_KNJIZENJA
		FROM PROMETNI_DOKUMENT
		WHERE PIB = @PIB AND GODINA = @GODINA AND BROJ_PROMETNOG_DOKUMENTA=@BROJ_PROMETNOG_DOKUMENTA) > GETDATE()
	BEGIN
		RAISERROR('Datum nastanka ne sme biti veci od danasnjeg', 11, 2)
		RETURN
	END
			
	DECLARE
		@C_PIB char(12),
		@C_GODINA numeric(4),
		@C_BROJ_PROMETNOG_DOKUMENTA numeric(5),
		@C_SIFRA_ARTIKLA char(4),
		@C_RBR numeric(3),
		@C_KOLICINA decimal(12,4),
		@C_CENA decimal(14,2), 
		@C_VREDNOST decimal(14,2)
					
	SET @BROJ_TRANSAKCIJA = @@TRANCOUNT
	
	IF (@BROJ_TRANSAKCIJA = 0)
	BEGIN TRANSACTION

		DECLARE cursSTAVKE CURSOR FOR
		SELECT PIB, GODINA, BROJ_PROMETNOG_DOKUMENTA, SIFRA_ARTIKLA, RBR,
			KOLICINA, CENA, VREDNOST
			FROM STAVKA_PROMETNOG_DOKUMENTA
			WHERE BROJ_PROMETNOG_DOKUMENTA = @BROJ_PROMETNOG_DOKUMENTA AND PIB=@PIB AND GODINA=@GODINA
				
		OPEN cursSTAVKE
		FETCH NEXT FROM cursSTAVKE INTO @C_PIB, @C_GODINA, @C_BROJ_PROMETNOG_DOKUMENTA, @C_SIFRA_ARTIKLA, @C_RBR,
			@C_KOLICINA, @C_CENA, @C_VREDNOST
			
		WHILE @@FETCH_STATUS=0
		BEGIN
		
			DECLARE
				@SIFRA_OBJEKTA char(12)
			
			SET @SIFRA_OBJEKTA = (SELECT SIFRA_OBJEKTA FROM PROMETNI_DOKUMENT 
				WHERE BROJ_PROMETNOG_DOKUMENTA=@BROJ_PROMETNOG_DOKUMENTA AND PIB = @PIB AND GODINA = @GODINA)
			
			IF (SELECT COUNT(*)
				FROM MAGACINSAK_KARTICA
				WHERE PIB = @C_PIB AND SIFRA_OBJEKTA = @SIFRA_OBJEKTA AND SIFRA_ARTIKLA = @C_SIFRA_ARTIKLA AND GODINA = @C_GODINA) > 0
			BEGIN
				UPDATE